apiVersion: v1
kind: Pod
metadata:
 name: memory-empty-pod
spec:
 containers:
  - name: app
    image: ubuntu
    command:
     - sh
     - -c
     - sleep 3600 
    volumeMounts:
     - name: memory-storage
       mountPath: /cache
 volumes:
  - name: memory-storage
    emptyDir: 
     medium: Memory
