apiVersion: v1
kind: Pod
metadata:
 name: pv-demo-pod
spec:
 containers:
  - name: app
    image: busybox
    command:
     - sh
     - -c
     - sleep 3600
    volumeMounts:
     - name: persistent-storage
       mountPath: /data

 volumes:
  - name: persistent-storage
    persistentVolumeClaim:
     claimName: demo-pvc
