apiVersion: v1
kind: Pod
metadata:
 name: two-containers-pod
spec:
 containers:
  - name: web
    image: nginx:latest
  - name: client
    image: curlimages/curl
    command:
     - sleep
     - "3600"
